services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - ./api/.env
    depends_on:
      - postgres
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: vite_app
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    command: sh -c "npm install && npm run host"
    depends_on:
      - api
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file:
      - ./api/.env
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/root/.pgadmin
    env_file:
      - ./api/.env
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
